# Azure DevOps CI/CD Pipeline for World Cup Simulator
# This pipeline builds both frontend (Angular) and backend (.NET), runs tests, and deploys to Azure

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - frontend/*
      - backend/*

pr:
  branches:
    include:
      - main
      - develop

variables:
  - group: worldcup-simulator-secrets  # Variable group containing secrets
  
  # Build configuration
  - name: buildConfiguration
    value: 'Release'
  - name: nodeVersion
    value: '20.x'
  - name: dotnetVersion
    value: '9.0.x'
  
  # Azure resource names
  - name: azureSubscription
    value: 'azure-worldcup-simulator'
  - name: frontendAppName
    value: 'worldcup-simulator-frontend-dev'
  - name: backendAppName
    value: 'worldcup-simulator-backend-dev'
  - name: resourceGroupName
    value: 'rg-worldcup-simulator-dev'
  - name: sqlServerName
    value: 'sql-worldcup-simulator-dev'
  - name: sqlDatabaseName
    value: 'worldcup-db-dev'
  
  # Environment-specific API URLs
  - name: apiUrl
    value: 'https://worldcup-simulator-backend-dev.azurewebsites.net'
  - name: environmentName
    value: 'Development'

stages:
  # ============================================
  # STAGE 1: BUILD & TEST
  # ============================================
  - stage: Build
    displayName: 'Build and Test'
    jobs:
      # Frontend Build Job
      - job: BuildFrontend
        displayName: 'Build Angular Frontend'
        pool:
          name: 'Default'  # Use self-hosted agent pool
        steps:
          - task: PowerShell@2
            displayName: 'Clean agent workspace'
            inputs:
              targetType: 'inline'
              script: |
                Remove-Item -Path "$(Agent.BuildDirectory)\*" -Recurse -Force -ErrorAction SilentlyContinue
                Write-Host "Workspace cleaned"
          
          - checkout: self
            clean: true
            fetchDepth: 1
            displayName: 'Checkout repository (clean)'
          
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: $(nodeVersion)

          - task: Npm@1
            displayName: 'npm install'
            inputs:
              command: 'install'
              workingDir: 'world-cup-simulator/frontend'

          - task: PowerShell@2
            displayName: 'Build and configure frontend'
            inputs:
              targetType: 'filePath'
              filePath: 'world-cup-simulator/frontend/deploy.ps1'
              arguments: '-ApiUrl "$(apiUrl)"'
              workingDirectory: 'world-cup-simulator/frontend'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish frontend artifact'
            inputs:
              PathtoPublish: 'world-cup-simulator/frontend/dist/world-cup-simulator'
              ArtifactName: 'frontend-drop'
              publishLocation: 'Container'

      # Backend Build Job
      - job: BuildBackend
        displayName: 'Build .NET Backend'
        pool:
          name: 'Default'  # Self-hosted agent
        steps:
          - checkout: self
            displayName: 'Checkout repository'
          
          - task: UseDotNet@2
            displayName: 'Install .NET SDK'
            inputs:
              version: $(dotnetVersion)

          - task: DotNetCoreCLI@2
            displayName: 'Restore NuGet packages'
            inputs:
              command: 'restore'
              projects: 'world-cup-simulator/backend/**/*.csproj'

          - task: DotNetCoreCLI@2
            displayName: 'Build backend'
            inputs:
              command: 'build'
              projects: 'world-cup-simulator/backend/**/*.csproj'
              arguments: '--configuration $(buildConfiguration) --no-restore'

          - task: DotNetCoreCLI@2
            displayName: 'Run backend tests'
            inputs:
              command: 'test'
              projects: 'world-cup-simulator/backend/**/*Tests.csproj'
              arguments: '--configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage"'

          - task: DotNetCoreCLI@2
            displayName: 'Publish backend'
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: 'world-cup-simulator/backend/WorldCupSimulator.Api/WorldCupSimulator.Api.csproj'
              arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/backend'
              zipAfterPublish: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish backend artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/backend'
              ArtifactName: 'backend-drop'
              publishLocation: 'Container'

  # ============================================
  # STAGE 2: DEPLOY TO AZURE
  # ============================================
  - stage: Deploy
    displayName: 'Deploy to Azure'
    dependsOn: Build
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/develop')))
    jobs:
      # Database Migration Job
      - job: DatabaseMigration
        displayName: 'Apply Database Migrations'
        pool:
          name: 'Default'  # Self-hosted agent
        steps:
          - checkout: self
            displayName: 'Checkout repository'
          
          - task: UseDotNet@2
            displayName: 'Install .NET SDK'
            inputs:
              version: $(dotnetVersion)

          - task: PowerShell@2
            displayName: 'Install EF Core tools'
            inputs:
              targetType: 'inline'
              script: |
                dotnet tool install --global dotnet-ef
                dotnet ef --version

          - task: PowerShell@2
            displayName: 'Get SQL connection string'
            inputs:
              targetType: 'inline'
              script: |
                # Build connection string directly without Azure CLI (avoids CLI dependency issues)
                # Uses variables from worldcup-simulator-secrets variable group
                $sqlServer = "$(sqlServerName).database.windows.net"
                $database = "$(sqlDatabaseName)"
                $username = "$(sqlServerAdminUser)"
                $password = "$(sqlServerAdminPassword)"
                
                $connectionString = "Server=tcp:$sqlServer,1433;Initial Catalog=$database;Persist Security Info=False;User ID=$username;Password=$password;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
                
                Write-Host "##vso[task.setvariable variable=ConnectionString;issecret=true]$connectionString"
                Write-Host "Connection string configured for: $database on $sqlServer"

          - task: PowerShell@2
            displayName: 'Apply EF Core migrations'
            inputs:
              targetType: 'inline'
              script: |
                cd world-cup-simulator/backend/WorldCupSimulator.Api
                dotnet ef database update --connection "$(ConnectionString)" --verbose
              workingDirectory: '$(System.DefaultWorkingDirectory)'

      # Backend Deployment Job
      - job: DeployBackend
        displayName: 'Deploy Backend to App Service'
        dependsOn: DatabaseMigration
        pool:
          name: 'Default'  # Self-hosted agent
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download backend artifact'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'backend-drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy to Azure App Service'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: $(azureSubscription)
              appType: 'webApp'
              WebAppName: $(backendAppName)
              packageForLinux: '$(System.ArtifactsDirectory)/backend-drop/*.zip'
              RuntimeStack: 'DOTNET|9.0'

          - task: AzureAppServiceSettings@1
            displayName: 'Configure App Settings'
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(backendAppName)
              resourceGroupName: $(resourceGroupName)
              appSettings: |
                [
                  {
                    "name": "ASPNETCORE_ENVIRONMENT",
                    "value": "$(environmentName)",
                    "slotSetting": false
                  }
                ]

      # Frontend Deployment Job
      - job: DeployFrontend
        displayName: 'Deploy Frontend to Azure'
        dependsOn: DeployBackend
        pool:
          name: 'Default'  # Self-hosted agent
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download frontend artifact'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'frontend-drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          # Option A: Deploy to Azure Static Web Apps (recommended for Angular)
          - task: AzureStaticWebApp@0
            displayName: 'Deploy to Azure Static Web Apps'
            inputs:
              app_location: '$(System.ArtifactsDirectory)/frontend-drop'
              skip_app_build: true
              azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)

          # Option B: Deploy to Azure App Service (alternative)
          # - task: AzureRmWebAppDeployment@4
          #   displayName: 'Deploy to App Service'
          #   inputs:
          #     ConnectionType: 'AzureRM'
          #     azureSubscription: $(azureSubscription)
          #     appType: 'webApp'
          #     WebAppName: $(frontendAppName)
          #     packageForLinux: '$(System.ArtifactsDirectory)/frontend-drop'

  # ============================================
  # STAGE 3: SMOKE TESTS (Optional)
  # ============================================
  - stage: SmokeTests
    displayName: 'Post-Deployment Smoke Tests'
    dependsOn: Deploy
    condition: succeeded()
    jobs:
      - job: RunSmokeTests
        displayName: 'Run smoke tests'
        pool:
          name: 'Default'  # Self-hosted agent
        steps:
          - task: PowerShell@2
            displayName: 'Test backend health endpoint'
            inputs:
              targetType: 'inline'
              script: |
                $backendUrl = "$(apiUrl)/health"
                Write-Host "Testing backend at: $backendUrl"
                
                try {
                  $response = Invoke-WebRequest -Uri $backendUrl -UseBasicParsing
                  if ($response.StatusCode -eq 200) {
                    Write-Host "✓ Backend is healthy" -ForegroundColor Green
                  } else {
                    Write-Error "✗ Backend returned status code: $($response.StatusCode)"
                    exit 1
                  }
                } catch {
                  Write-Error "✗ Failed to reach backend: $_"
                  exit 1
                }

          - task: PowerShell@2
            displayName: 'Test frontend accessibility'
            inputs:
              targetType: 'inline'
              script: |
                $frontendUrl = "https://$(frontendAppName).azurewebsites.net"
                Write-Host "Testing frontend at: $frontendUrl"
                
                try {
                  $response = Invoke-WebRequest -Uri $frontendUrl -UseBasicParsing
                  if ($response.StatusCode -eq 200) {
                    Write-Host "✓ Frontend is accessible" -ForegroundColor Green
                  } else {
                    Write-Error "✗ Frontend returned status code: $($response.StatusCode)"
                    exit 1
                  }
                } catch {
                  Write-Error "✗ Failed to reach frontend: $_"
                  exit 1
                }
